import crypto from 'node:crypto';
import {
  Edge,
  ENTRYPOINT_BASE,
  ExtensionNode,
  IVRNode,
  Membership,
  PbxNode,
  QueueNode,
  QueueStrategy,
  RingGroupNode,
  ScheduleNode,
  ScheduleWeekday,
  Topology,
  VoicemailNode,
} from '@visual-pbx/shared';

// Translates a validated Topology into Asterisk config snippets.
// These are written as *_generated.conf and #include'd from the static base
// config that ships in the asterisk image (see asterisk/conf-templates).

export interface GeneratedConfigs {
  pjsip: string;
  extensions: string;
  queues: string;
  voicemail: string;
}

const HEADER = '; AUTO-GENERATED by Essentials+ Calls backend. Do not edit by hand.';

function display(value: string): string {
  return value.replace(/[\r\n\0;,\[\]"]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 120);
}

function configValue(value: string, field: string): string {
  if (!value || /[\r\n\0;\[\]]/.test(value)) throw new Error(`${field} enthält für Asterisk unzulässige Zeichen.`);
  return value;
}

export function sanitize(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_');
}

function nodeId(id: string): string {
  return `node_${sanitize(id)}`;
}

/**
 * PJSIP object name for an extension — derived from the SIP user, not the node id.
 *
 * Asterisk identifies an incoming request by matching the SIP username against
 * the *endpoint name* (`identify_by` defaults to `username,ip`). Naming
 * endpoints after the node id made every registration fail with "No matching
 * endpoint found", because the phone authenticates as e.g. `101` while the
 * endpoint was called `ext_101`.
 */
export function endpointName(ext: ExtensionNode): string {
  return sanitize(ext.properties.sipUser);
}

function ctxId(id: string): string {
  return `ivr_${sanitize(id)}`;
}

function extensionNodes(topology: Topology): ExtensionNode[] {
  return topology.nodes.filter((n): n is ExtensionNode => n.type === 'extension');
}

function outgoing(topology: Topology, sourceId: string): Edge[] {
  return topology.edges.filter((e) => e.source === sourceId);
}

function findEdgeByCondition(edges: Edge[], type: 'timeout' | 'invalid'): Edge | undefined {
  return edges.find((e) => e.condition?.type === type);
}

function findFallbackEdge(edges: Edge[]): Edge | undefined {
  return edges.find((e) => e.condition?.type === 'timeout' || e.condition?.type === 'unconditional' || !e.condition);
}

function membersOf(topology: Topology, groupId: string): { membership: Membership; ext: ExtensionNode }[] {
  return topology.memberships
    .filter((m) => m.groupId === groupId)
    .map((m) => ({ membership: m, ext: topology.nodes.find((n) => n.id === m.memberId) as ExtensionNode }))
    .filter((x) => x.ext && x.ext.type === 'extension')
    .sort((a, b) => (a.membership.position ?? 0) - (b.membership.position ?? 0));
}

export function generatePjsipConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  for (const ext of extensionNodes(topology)) {
    const id = endpointName(ext);
    const { number, sipUser, sipPassword, callerIdName } = ext.properties;
    if (!sipPassword) throw new Error(`SIP-Secret für Extension "${ext.id}" ist nicht konfiguriert.`);
    // remove_existing: with max_contacts=1 and no replacement policy, a phone
    // that re-registers from a new source port (restart, network change) is
    // rejected with "will exceed max contacts" until the old contact expires.
    // ContactStatus events still report registration and expiration. Active
    // OPTIONS qualification is disabled by default because a valid SIP client
    // is not required to implement unsolicited OPTIONS; operators may add it
    // later as an explicit reachability policy.
    lines.push(`[${id}]`, 'type=aor', 'max_contacts=1', 'remove_existing=yes', 'qualify_frequency=0', '');
    lines.push(
      `[${id}]`,
      'type=auth',
      // Asterisk 18 predates password_digest but supports the equivalent
      // pre-computed MD5 HA1 credential. The plaintext remains transient in
      // memory and never lands in the generated PJSIP configuration.
      'auth_type=md5',
      'realm=asterisk',
      `username=${configValue(sipUser, 'sipUser')}`,
      `md5_cred=${crypto.createHash('md5').update(`${sipUser}:asterisk:${configValue(sipPassword, 'sipPassword')}`).digest('hex')}`,
      ''
    );
    lines.push(
      `[${id}]`,
      'type=endpoint',
      'context=internal',
      'disallow=all',
      'allow=ulaw,alaw',
      // Keep media anchored in the isolated Asterisk runtime. Besides making
      // IVR/queue behavior deterministic, this prevents native-bridge
      // re-INVITEs from bypassing the synthetic RTP observer.
      'direct_media=no',
      `auth=${id}`,
      `aors=${id}`,
      `callerid="${display(callerIdName ?? ext.label)}" <${number}>`,
      ''
    );
  }

  return lines.join('\n');
}

export function generateVoicemailConf(topology: Topology): string {
  // Included from inside the [default] context opened in the static voicemail.conf.
  const lines: string[] = [HEADER, ''];

  for (const ext of extensionNodes(topology)) {
    const vm = ext.properties.voicemail;
    if (vm?.enabled) {
      lines.push(`${vm.mailbox} => ${configValue(vm.pin ?? '0000', 'voicemail pin')},${display(ext.label)},${display(vm.email ?? '')}`);
    }
  }

  for (const node of topology.nodes) {
    if (node.type === 'voicemail') {
      const vm = node as VoicemailNode;
      lines.push(
        `${vm.properties.mailbox} => ${configValue(vm.properties.pin ?? '0000', 'voicemail pin')},${display(vm.label)},${display(
          vm.properties.email ?? ''
        )}`
      );
    }
  }

  return lines.join('\n');
}

/**
 * `roundrobin` was removed from Asterisk in 12.x; `rrmemory` is its successor.
 * Passing the old name makes app_queue fall back to ringall with a warning,
 * so we translate it here instead of silently changing behaviour.
 */
function queueStrategy(strategy: QueueStrategy): string {
  return strategy === 'roundrobin' ? 'rrmemory' : strategy;
}

export function generateQueuesConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  for (const node of topology.nodes) {
    if (node.type !== 'queue') continue;
    const queue = node as QueueNode;
    const id = sanitize(queue.id);
    lines.push(
      `[${id}]`,
      'musiconhold=default',
      `strategy=${queueStrategy(queue.properties.strategy)}`,
      `timeout=${queue.properties.timeout}`,
      'maxlen=0',
      `joinempty=${queue.properties.joinEmpty}`,
      `leavewhenempty=${queue.properties.leaveWhenEmpty}`
    );
    for (const { ext } of membersOf(topology, queue.id)) {
      lines.push(`member => PJSIP/${endpointName(ext)},0,${display(ext.label)}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateIvrContext(topology: Topology, ivr: IVRNode): string[] {
  const lines: string[] = [];
  const edges = outgoing(topology, ivr.id);
  const timeoutEdge = findEdgeByCondition(edges, 'timeout');
  const invalidEdge = findEdgeByCondition(edges, 'invalid');
  const digitEdges = edges.filter((e) => e.condition?.type === 'digit');
  const retryVar = `RETRY_${sanitize(ivr.id)}`;

  lines.push(`[${ctxId(ivr.id)}]`);
  // The retry counter is initialised once on entry. Re-prompting jumps to the
  // (menu) label rather than priority 1, otherwise the counter would reset on
  // every invalid entry and the caller could loop forever.
  lines.push(`exten => s,1,NoOp(IVR ${display(ivr.label)})`);
  lines.push(` same => n,Set(${retryVar}=0)`);
  lines.push(` same => n(menu),Background(${configValue(ivr.properties.greeting, 'IVR greeting')})`);
  lines.push(` same => n,WaitExten(${ivr.properties.timeout})`);

  for (const edge of digitEdges) {
    const condition = edge.condition!;
    const digit = condition.type === 'digit' ? condition.value : '';
    lines.push(`exten => ${digit},1,Goto(callflow,${nodeId(edge.target)},1)`);
  }

  lines.push('exten => t,1,NoOp(IVR timeout)');
  lines.push(timeoutEdge ? ` same => n,Goto(callflow,${nodeId(timeoutEdge.target)},1)` : ' same => n,Hangup()');

  // Asterisk has no shell-style `${VAR:-default}` — `:-0` is substring syntax and
  // yields an empty string, which makes `$[ + 1]` a parse error. The counter is
  // initialised in `s`, but the `0${VAR}` prefix keeps the arithmetic valid even
  // if the extension is ever reached without passing through `s`.
  lines.push(`exten => i,1,Set(${retryVar}=$[0\${${retryVar}} + 1])`);
  lines.push(' same => n,Playback(invalid)');
  lines.push(
    ` same => n,GotoIf($[0\${${retryVar}} >= ${ivr.properties.invalidRetries}]?${
      invalidEdge ? `callflow,${nodeId(invalidEdge.target)},1` : `${ctxId(ivr.id)},giveup,1`
    })`
  );
  lines.push(` same => n,Goto(${ctxId(ivr.id)},s,menu)`);
  lines.push('exten => giveup,1,Hangup()');
  lines.push('');

  return lines;
}

function generateCallflowEntry(topology: Topology, node: PbxNode): string[] {
  const lines: string[] = [];
  const edges = outgoing(topology, node.id);
  const fallback = findFallbackEdge(edges);

  const finish = (voicemailMailbox?: string) => {
    if (fallback) {
      lines.push(` same => n,Goto(callflow,${nodeId(fallback.target)},1)`);
    } else if (voicemailMailbox) {
      lines.push(` same => n,VoiceMail(${voicemailMailbox}@default,u)`);
    }
    lines.push(' same => n,Hangup()');
  };

  switch (node.type) {
    case 'ivr': {
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Enter IVR ${display(node.label)})`);
      lines.push(` same => n,Goto(${ctxId(node.id)},s,1)`);
      break;
    }
    case 'extension': {
      const ext = node as ExtensionNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Route to extension ${display(ext.label)})`);
      lines.push(` same => n,Dial(PJSIP/${endpointName(ext)},20)`);
      finish(ext.properties.voicemail?.enabled ? ext.properties.voicemail.mailbox : undefined);
      break;
    }
    case 'ringgroup': {
      const rg = node as RingGroupNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Ring Group ${display(rg.label)} ${rg.properties.strategy})`);
      lines.push(...ringGroupDialLines(topology, rg));
      finish();
      break;
    }
    case 'queue': {
      const queue = node as QueueNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Queue ${display(queue.label)})`);
      // Queue(name, options, URL, announceoverride, timeout): the 5th argument is
      // the overall wait limit. queues.conf `timeout` is only the per-agent ring
      // time, so maxWaitTime has to be passed here or it has no effect at all.
      lines.push(` same => n,Queue(${sanitize(queue.id)},,,,${queue.properties.maxWaitTime})`);
      finish();
      break;
    }
    case 'schedule': {
      lines.push(...scheduleDialplan(topology, node));
      break;
    }
    case 'voicemail': {
      const vm = node as VoicemailNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Voicemail ${display(vm.label)})`);
      lines.push(` same => n,VoiceMail(${vm.properties.mailbox}@default,u)`);
      lines.push(' same => n,Hangup()');
      break;
    }
    default:
      break;
  }

  lines.push('');
  return lines;
}

const ASTERISK_WEEKDAY: Record<ScheduleWeekday, string> = {
  1: 'mon',
  2: 'tue',
  3: 'wed',
  4: 'thu',
  5: 'fri',
  6: 'sat',
  7: 'sun',
};

function previousMinute(value: string): string {
  const [hour, minute] = value.split(':').map(Number);
  const total = (hour * 60 + minute + 24 * 60 - 1) % (24 * 60);
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`;
}

function scheduleDialplan(topology: Topology, schedule: ScheduleNode): string[] {
  const edges = outgoing(topology, schedule.id);
  const openEdge = edges.find((edge) => edge.condition?.type === 'open');
  const closedEdge = edges.find((edge) => edge.condition?.type === 'closed');
  const timezone = configValue(schedule.properties.timezone, 'schedule timezone');
  const lines = [`exten => ${nodeId(schedule.id)},1,NoOp(Schedule ${display(schedule.label)} ${timezone})`];

  if (!openEdge || !closedEdge) {
    lines.push(' same => n,Hangup()');
    return lines;
  }

  for (const holiday of schedule.properties.holidays) {
    lines.push(
      ` same => n,GotoIf($["\${STRFTIME(\${EPOCH},${timezone},%Y-%m-%d)}" = "${holiday}"]?callflow,${nodeId(
        closedEdge.target
      )},1)`
    );
  }

  for (const window of schedule.properties.windows) {
    const startMinutes = Number(window.start.slice(0, 2)) * 60 + Number(window.start.slice(3));
    const endMinutes = Number(window.end.slice(0, 2)) * 60 + Number(window.end.slice(3));
    const weekdays = window.weekdays.map((day) => ASTERISK_WEEKDAY[day]).join('&');
    if (startMinutes < endMinutes) {
      lines.push(
        ` same => n,GotoIfTime(${window.start}-${previousMinute(window.end)},${weekdays},*,*,${timezone}?callflow,${nodeId(
          openEdge.target
        )},1)`
      );
    } else {
      lines.push(
        ` same => n,GotoIfTime(${window.start}-23:59,${weekdays},*,*,${timezone}?callflow,${nodeId(openEdge.target)},1)`
      );
      const following = window.weekdays.map((day) => ASTERISK_WEEKDAY[day === 7 ? 1 : ((day + 1) as ScheduleWeekday)]).join('&');
      lines.push(
        ` same => n,GotoIfTime(00:00-${previousMinute(window.end)},${following},*,*,${timezone}?callflow,${nodeId(
          openEdge.target
        )},1)`
      );
    }
  }
  lines.push(` same => n,Goto(callflow,${nodeId(closedEdge.target)},1)`);
  return lines;
}

/**
 * `ringall` rings every member in parallel. The other strategies are ordered,
 * which plain Dial() cannot express, so they are approximated by dialling the
 * members one after another in membership order — each for the group's ring
 * timeout. Without this the strategy field would have no effect whatsoever.
 */
function ringGroupDialLines(topology: Topology, rg: RingGroupNode): string[] {
  const members = membersOf(topology, rg.id).map(({ ext }) => `PJSIP/${endpointName(ext)}`);
  const timeout = rg.properties.ringTimeout;

  if (members.length === 0) {
    // Validation rejects member-less groups, but the generator must not emit
    // a syntactically broken Dial() if it is ever called on unvalidated input.
    return [' same => n,NoOp(Ring group has no members)'];
  }

  if (rg.properties.strategy === 'ringall') {
    return [` same => n,Dial(${members.join('&')},${timeout})`];
  }

  return members.map((m) => ` same => n,Dial(${m},${timeout})`);
}

export function generateExtensionsConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  lines.push('[internal]');
  // Endpoints register into [internal], so the test entry points have to be
  // reachable from here — otherwise dialling them just fails.
  lines.push('include => entrypoints');
  for (const ext of extensionNodes(topology)) {
    const fallback = findFallbackEdge(outgoing(topology, ext.id));
    lines.push(`exten => ${ext.properties.number},1,NoOp(Calling ${display(ext.label)})`);
    lines.push(` same => n,Dial(PJSIP/${endpointName(ext)},20)`);
    if (fallback) {
      lines.push(` same => n,Goto(callflow,${nodeId(fallback.target)},1)`);
    } else if (ext.properties.voicemail?.enabled) {
      lines.push(` same => n,VoiceMail(${ext.properties.voicemail.mailbox}@default,u)`);
    }
    lines.push(' same => n,Hangup()');
  }
  lines.push('');

  // Entry points for testing: dial 600 + index to reach any node without inbound
  // trunk/DID routing (trunk/external node types are disabled in the PoC).
  lines.push('[entrypoints]');
  topology.nodes.forEach((node, i) => {
    lines.push(`exten => ${ENTRYPOINT_BASE + i},1,Goto(callflow,${nodeId(node.id)},1)  ; ${node.type} ${display(node.label)}`);
  });
  lines.push('');

  lines.push('[callflow]');
  for (const node of topology.nodes) {
    lines.push(...generateCallflowEntry(topology, node));
  }

  for (const node of topology.nodes) {
    if (node.type === 'ivr') {
      lines.push(...generateIvrContext(topology, node as IVRNode));
    }
  }

  return lines.join('\n');
}

export function generateAll(topology: Topology): GeneratedConfigs {
  return {
    pjsip: generatePjsipConf(topology),
    extensions: generateExtensionsConf(topology),
    queues: generateQueuesConf(topology),
    voicemail: generateVoicemailConf(topology),
  };
}
