import {
  Edge,
  ENTRYPOINT_BASE,
  ExtensionNode,
  IVRNode,
  Membership,
  PbxNode,
  QueueNode,
  QueueStrategy,
  RingGroupNode,
  Topology,
  VoicemailNode,
} from '@visual-pbx/shared';

// Translates a validated Topology into Asterisk config snippets.
// These are written as *_generated.conf and #include'd from the static base
// config that ships in the asterisk image (see asterisk/conf-templates).

export interface GeneratedConfigs {
  pjsip: string;
  extensions: string;
  queues: string;
  voicemail: string;
}

const HEADER = '; AUTO-GENERATED by visual-pbx backend. Do not edit by hand.';

export function sanitize(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_');
}

function nodeId(id: string): string {
  return `node_${sanitize(id)}`;
}

function ctxId(id: string): string {
  return `ivr_${sanitize(id)}`;
}

function extensionNodes(topology: Topology): ExtensionNode[] {
  return topology.nodes.filter((n): n is ExtensionNode => n.type === 'extension');
}

function outgoing(topology: Topology, sourceId: string): Edge[] {
  return topology.edges.filter((e) => e.source === sourceId);
}

function findEdgeByCondition(edges: Edge[], type: 'timeout' | 'invalid'): Edge | undefined {
  return edges.find((e) => e.condition?.type === type);
}

function findFallbackEdge(edges: Edge[]): Edge | undefined {
  return edges.find((e) => e.condition?.type === 'timeout' || e.condition?.type === 'unconditional' || !e.condition);
}

function membersOf(topology: Topology, groupId: string): { membership: Membership; ext: ExtensionNode }[] {
  return topology.memberships
    .filter((m) => m.groupId === groupId)
    .map((m) => ({ membership: m, ext: topology.nodes.find((n) => n.id === m.memberId) as ExtensionNode }))
    .filter((x) => x.ext && x.ext.type === 'extension')
    .sort((a, b) => (a.membership.position ?? 0) - (b.membership.position ?? 0));
}

export function generatePjsipConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  for (const ext of extensionNodes(topology)) {
    const id = sanitize(ext.id);
    const { number, sipUser, sipPassword, callerIdName } = ext.properties;
    lines.push(`[${id}]`, 'type=aor', 'max_contacts=1', '');
    lines.push(`[${id}]`, 'type=auth', 'auth_type=userpass', `username=${sipUser}`, `password=${sipPassword}`, '');
    lines.push(
      `[${id}]`,
      'type=endpoint',
      'context=internal',
      'disallow=all',
      'allow=ulaw,alaw',
      `auth=${id}`,
      `aors=${id}`,
      `callerid="${callerIdName ?? ext.label}" <${number}>`,
      ''
    );
  }

  return lines.join('\n');
}

export function generateVoicemailConf(topology: Topology): string {
  // Included from inside the [default] context opened in the static voicemail.conf.
  const lines: string[] = [HEADER, ''];

  for (const ext of extensionNodes(topology)) {
    const vm = ext.properties.voicemail;
    if (vm?.enabled) {
      lines.push(`${vm.mailbox} => ${vm.pin ?? '0000'},${ext.label},${vm.email ?? ''}`);
    }
  }

  for (const node of topology.nodes) {
    if (node.type === 'voicemail') {
      const vm = node as VoicemailNode;
      lines.push(`${vm.properties.mailbox} => ${vm.properties.pin ?? '0000'},${vm.label},${vm.properties.email ?? ''}`);
    }
  }

  return lines.join('\n');
}

/**
 * `roundrobin` was removed from Asterisk in 12.x; `rrmemory` is its successor.
 * Passing the old name makes app_queue fall back to ringall with a warning,
 * so we translate it here instead of silently changing behaviour.
 */
function queueStrategy(strategy: QueueStrategy): string {
  return strategy === 'roundrobin' ? 'rrmemory' : strategy;
}

export function generateQueuesConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  for (const node of topology.nodes) {
    if (node.type !== 'queue') continue;
    const queue = node as QueueNode;
    const id = sanitize(queue.id);
    lines.push(
      `[${id}]`,
      'musiconhold=default',
      `strategy=${queueStrategy(queue.properties.strategy)}`,
      `timeout=${queue.properties.timeout}`,
      'maxlen=0',
      `joinempty=${queue.properties.joinEmpty}`,
      `leavewhenempty=${queue.properties.leaveWhenEmpty}`
    );
    for (const { ext } of membersOf(topology, queue.id)) {
      lines.push(`member => PJSIP/${sanitize(ext.id)},0,${ext.label}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateIvrContext(topology: Topology, ivr: IVRNode): string[] {
  const lines: string[] = [];
  const edges = outgoing(topology, ivr.id);
  const timeoutEdge = findEdgeByCondition(edges, 'timeout');
  const invalidEdge = findEdgeByCondition(edges, 'invalid');
  const digitEdges = edges.filter((e) => e.condition?.type === 'digit');
  const retryVar = `RETRY_${sanitize(ivr.id)}`;

  lines.push(`[${ctxId(ivr.id)}]`);
  // The retry counter is initialised once on entry. Re-prompting jumps to the
  // (menu) label rather than priority 1, otherwise the counter would reset on
  // every invalid entry and the caller could loop forever.
  lines.push(`exten => s,1,NoOp(IVR ${ivr.label})`);
  lines.push(` same => n,Set(${retryVar}=0)`);
  lines.push(` same => n(menu),Background(${ivr.properties.greeting})`);
  lines.push(` same => n,WaitExten(${ivr.properties.timeout})`);

  for (const edge of digitEdges) {
    const condition = edge.condition!;
    const digit = condition.type === 'digit' ? condition.value : '';
    lines.push(`exten => ${digit},1,Goto(callflow,${nodeId(edge.target)},1)`);
  }

  lines.push('exten => t,1,NoOp(IVR timeout)');
  lines.push(timeoutEdge ? ` same => n,Goto(callflow,${nodeId(timeoutEdge.target)},1)` : ' same => n,Hangup()');

  // Asterisk has no shell-style `${VAR:-default}` — `:-0` is substring syntax and
  // yields an empty string, which makes `$[ + 1]` a parse error. The counter is
  // initialised in `s`, but the `0${VAR}` prefix keeps the arithmetic valid even
  // if the extension is ever reached without passing through `s`.
  lines.push(`exten => i,1,Set(${retryVar}=$[0\${${retryVar}} + 1])`);
  lines.push(' same => n,Playback(invalid)');
  lines.push(
    ` same => n,GotoIf($[0\${${retryVar}} >= ${ivr.properties.invalidRetries}]?${
      invalidEdge ? `callflow,${nodeId(invalidEdge.target)},1` : `${ctxId(ivr.id)},giveup,1`
    })`
  );
  lines.push(` same => n,Goto(${ctxId(ivr.id)},s,menu)`);
  lines.push('exten => giveup,1,Hangup()');
  lines.push('');

  return lines;
}

function generateCallflowEntry(topology: Topology, node: PbxNode): string[] {
  const lines: string[] = [];
  const edges = outgoing(topology, node.id);
  const fallback = findFallbackEdge(edges);

  const finish = (voicemailMailbox?: string) => {
    if (fallback) {
      lines.push(` same => n,Goto(callflow,${nodeId(fallback.target)},1)`);
    } else if (voicemailMailbox) {
      lines.push(` same => n,VoiceMail(${voicemailMailbox}@default,u)`);
    }
    lines.push(' same => n,Hangup()');
  };

  switch (node.type) {
    case 'ivr': {
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Enter IVR ${node.label})`);
      lines.push(` same => n,Goto(${ctxId(node.id)},s,1)`);
      break;
    }
    case 'extension': {
      const ext = node as ExtensionNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Route to extension ${ext.label})`);
      lines.push(` same => n,Dial(PJSIP/${sanitize(ext.id)},20)`);
      finish(ext.properties.voicemail?.enabled ? ext.properties.voicemail.mailbox : undefined);
      break;
    }
    case 'ringgroup': {
      const rg = node as RingGroupNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Ring Group ${rg.label} [${rg.properties.strategy}])`);
      lines.push(...ringGroupDialLines(topology, rg));
      finish();
      break;
    }
    case 'queue': {
      const queue = node as QueueNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Queue ${queue.label})`);
      // Queue(name, options, URL, announceoverride, timeout): the 5th argument is
      // the overall wait limit. queues.conf `timeout` is only the per-agent ring
      // time, so maxWaitTime has to be passed here or it has no effect at all.
      lines.push(` same => n,Queue(${sanitize(queue.id)},,,,${queue.properties.maxWaitTime})`);
      finish();
      break;
    }
    case 'voicemail': {
      const vm = node as VoicemailNode;
      lines.push(`exten => ${nodeId(node.id)},1,NoOp(Voicemail ${vm.label})`);
      lines.push(` same => n,VoiceMail(${vm.properties.mailbox}@default,u)`);
      lines.push(' same => n,Hangup()');
      break;
    }
    default:
      break;
  }

  lines.push('');
  return lines;
}

/**
 * `ringall` rings every member in parallel. The other strategies are ordered,
 * which plain Dial() cannot express, so they are approximated by dialling the
 * members one after another in membership order — each for the group's ring
 * timeout. Without this the strategy field would have no effect whatsoever.
 */
function ringGroupDialLines(topology: Topology, rg: RingGroupNode): string[] {
  const members = membersOf(topology, rg.id).map(({ ext }) => `PJSIP/${sanitize(ext.id)}`);
  const timeout = rg.properties.ringTimeout;

  if (members.length === 0) {
    // Validation rejects member-less groups, but the generator must not emit
    // a syntactically broken Dial() if it is ever called on unvalidated input.
    return [' same => n,NoOp(Ring group has no members)'];
  }

  if (rg.properties.strategy === 'ringall') {
    return [` same => n,Dial(${members.join('&')},${timeout})`];
  }

  return members.map((m) => ` same => n,Dial(${m},${timeout})`);
}

export function generateExtensionsConf(topology: Topology): string {
  const lines: string[] = [HEADER, ''];

  lines.push('[internal]');
  // Endpoints register into [internal], so the test entry points have to be
  // reachable from here — otherwise dialling them just fails.
  lines.push('include => entrypoints');
  for (const ext of extensionNodes(topology)) {
    const fallback = findFallbackEdge(outgoing(topology, ext.id));
    lines.push(`exten => ${ext.properties.number},1,NoOp(Calling ${ext.label})`);
    lines.push(` same => n,Dial(PJSIP/${sanitize(ext.id)},20)`);
    if (fallback) {
      lines.push(` same => n,Goto(callflow,${nodeId(fallback.target)},1)`);
    } else if (ext.properties.voicemail?.enabled) {
      lines.push(` same => n,VoiceMail(${ext.properties.voicemail.mailbox}@default,u)`);
    }
    lines.push(' same => n,Hangup()');
  }
  lines.push('');

  // Entry points for testing: dial 600 + index to reach any node without inbound
  // trunk/DID routing (trunk/external node types are disabled in the PoC).
  lines.push('[entrypoints]');
  topology.nodes.forEach((node, i) => {
    lines.push(`exten => ${ENTRYPOINT_BASE + i},1,Goto(callflow,${nodeId(node.id)},1)  ; ${node.type} "${node.label}"`);
  });
  lines.push('');

  lines.push('[callflow]');
  for (const node of topology.nodes) {
    lines.push(...generateCallflowEntry(topology, node));
  }

  for (const node of topology.nodes) {
    if (node.type === 'ivr') {
      lines.push(...generateIvrContext(topology, node as IVRNode));
    }
  }

  return lines.join('\n');
}

export function generateAll(topology: Topology): GeneratedConfigs {
  return {
    pjsip: generatePjsipConf(topology),
    extensions: generateExtensionsConf(topology),
    queues: generateQueuesConf(topology),
    voicemail: generateVoicemailConf(topology),
  };
}
