import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { Topology } from '@visual-pbx/shared';
import { Actor, PbxDatabase } from '../model/database';
import { GeneratedConfigs, generateAll } from './configGenerator';
import { AmiClient } from './amiClient';

function configOutDir(): string {
  return process.env.CONFIG_OUT_DIR ?? path.join(__dirname, '..', '..', 'data', 'generated');
}
const AMI_HOST = process.env.AMI_HOST ?? 'localhost';
const AMI_PORT = Number(process.env.AMI_PORT ?? 5038);
const AMI_USERNAME = process.env.AMI_USERNAME ?? 'visualpbx';

function amiSecret(): string {
  const secret = process.env.AMI_SECRET;
  if (!secret || secret === 'visualpbx') {
    throw new Error('AMI_SECRET fehlt oder verwendet den unsicheren historischen Defaultwert.');
  }
  return secret;
}

const CONFIG_FILES: Record<keyof GeneratedConfigs, string> = {
  pjsip: 'pjsip_generated.conf',
  extensions: 'extensions_generated.conf',
  queues: 'queues_generated.conf',
  voicemail: 'voicemail_generated.conf',
};

function configReaderGid(): number {
  const value = process.env.CONFIG_READER_GID;
  if (value === undefined) return process.getgid?.() ?? 0;
  if (!/^\d+$/.test(value)) throw new Error('CONFIG_READER_GID must be a numeric group id.');
  return Number(value);
}

function makeReadableByAsterisk(filePath: string, mode: number): void {
  fs.chmodSync(filePath, mode);
  fs.chownSync(filePath, process.getuid?.() ?? 0, configReaderGid());
}

let cachedClient: AmiClient | null = null;
let connecting: Promise<AmiClient> | null = null;

export async function getAmiClient(): Promise<AmiClient> {
  if (cachedClient?.connected) return cachedClient;
  if (connecting) return connecting;
  connecting = (async () => {
    const client = new AmiClient(AMI_HOST, AMI_PORT, AMI_USERNAME, amiSecret());
    client.once('closed', () => {
      if (cachedClient === client) cachedClient = null;
    });
    try {
      await client.connect();
      cachedClient = client;
      return client;
    } catch (error) {
      client.disconnect();
      throw error;
    } finally {
      connecting = null;
    }
  })();
  return connecting;
}

export function resetAmiClientForTests(): void {
  cachedClient?.disconnect();
  cachedClient = null;
  connecting = null;
}

export class GeneratedConfigValidationError extends Error {}

export function validateGeneratedConfigs(configs: GeneratedConfigs): void {
  const combinedBytes = Object.values(configs).reduce((sum, content) => sum + Buffer.byteLength(content), 0);
  if (combinedBytes > 4 * 1024 * 1024) throw new GeneratedConfigValidationError('Generierte Konfiguration ist unerwartet groß.');
  for (const [kind, content] of Object.entries(configs)) {
    if (!content.startsWith('; AUTO-GENERATED by Simple Calls')) {
      throw new GeneratedConfigValidationError(`${kind}: Generator-Header fehlt.`);
    }
    if (content.includes('\0') || /\r/.test(content)) {
      throw new GeneratedConfigValidationError(`${kind}: ungültige Steuerzeichen.`);
    }
    if (/^(?:#include|#exec|\s*system\s*=)/im.test(content)) {
      throw new GeneratedConfigValidationError(`${kind}: unerlaubte Include-/Exec-Anweisung.`);
    }
    for (const [index, line] of content.split('\n').entries()) {
      if (line.length > 2048) throw new GeneratedConfigValidationError(`${kind}:${index + 1}: Zeile ist zu lang.`);
      if (/^\[[^\]]*$/.test(line)) throw new GeneratedConfigValidationError(`${kind}:${index + 1}: Abschnitt ist nicht geschlossen.`);
    }
  }
  if (!configs.extensions.includes('[internal]') || !configs.extensions.includes('[callflow]')) {
    throw new GeneratedConfigValidationError('Dialplan enthält die Pflichtkontexte nicht.');
  }
}

function checksum(configs: GeneratedConfigs): string {
  const hash = crypto.createHash('sha256');
  for (const key of Object.keys(CONFIG_FILES) as Array<keyof GeneratedConfigs>) {
    hash.update(key).update('\0').update(configs[key]).update('\0');
  }
  return hash.digest('hex');
}

function currentLink(): string {
  return path.join(configOutDir(), 'current');
}

function readCurrentTarget(): string | null {
  try {
    return fs.readlinkSync(currentLink());
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT' || (error as NodeJS.ErrnoException).code === 'EINVAL') return null;
    throw error;
  }
}

function switchCurrent(target: string | null, deploymentId: string): void {
  const link = currentLink();
  if (target === null) {
    try {
      fs.unlinkSync(link);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    return;
  }
  const temp = path.join(configOutDir(), `.current-${deploymentId}`);
  fs.symlinkSync(target, temp, 'dir');
  fs.renameSync(temp, link);
}

export interface StagedConfig {
  deploymentId: string;
  target: string;
  checksum: string;
  directory: string;
}

function withDeploymentCanary(configs: GeneratedConfigs, deploymentId: string): GeneratedConfigs {
  return {
    ...configs,
    extensions: `${configs.extensions}\n\n[essentials_deploy_canary]\nexten => ${deploymentId},1,NoOp(ESSENTIALS_DEPLOYMENT_${deploymentId})\n same => n,Hangup()\n`,
  };
}

export function stageGeneratedConfigs(topology: Topology, deploymentId = crypto.randomUUID()): StagedConfig {
  if (process.env.PBX_TEST_FAIL_WRITE === 'true' && process.env.PBX_ENV === 'test') {
    throw new Error('Synthetic staged-config write failure');
  }
  if (!/^[A-Za-z0-9_-]{1,128}$/.test(deploymentId)) throw new Error('Ungültige Deployment-ID.');
  const configs = withDeploymentCanary(generateAll(topology), deploymentId);
  validateGeneratedConfigs(configs);
  const versionsDir = path.join(configOutDir(), 'versions');
  const stagingDir = path.join(versionsDir, `.staging-${deploymentId}`);
  const finalDir = path.join(versionsDir, deploymentId);
  fs.mkdirSync(versionsDir, { recursive: true, mode: 0o750 });
  makeReadableByAsterisk(versionsDir, 0o750);
  fs.mkdirSync(stagingDir, { recursive: false, mode: 0o750 });
  makeReadableByAsterisk(stagingDir, 0o750);
  try {
    for (const key of Object.keys(CONFIG_FILES) as Array<keyof GeneratedConfigs>) {
      const outputPath = path.join(stagingDir, CONFIG_FILES[key]);
      fs.writeFileSync(outputPath, configs[key], { encoding: 'utf8', mode: 0o640, flag: 'wx' });
      makeReadableByAsterisk(outputPath, 0o640);
    }
    const manifestPath = path.join(stagingDir, 'manifest.json');
    fs.writeFileSync(
      manifestPath,
      JSON.stringify({ deploymentId, checksum: checksum(configs), files: CONFIG_FILES }, null, 2),
      { encoding: 'utf8', mode: 0o640, flag: 'wx' }
    );
    makeReadableByAsterisk(manifestPath, 0o640);
    fs.renameSync(stagingDir, finalDir);
  } catch (error) {
    fs.rmSync(stagingDir, { recursive: true, force: true });
    throw error;
  }
  return {
    deploymentId,
    target: path.relative(configOutDir(), finalDir),
    checksum: checksum(configs),
    directory: finalDir,
  };
}

function wait(milliseconds: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

export async function validateStagedWithAsterisk(staged: StagedConfig): Promise<void> {
  const preflightDir = process.env.ASTERISK_PREFLIGHT_DIR;
  if (!preflightDir) {
    if (process.env.PBX_REQUIRE_ASTERISK_PREFLIGHT === 'true') {
      throw new GeneratedConfigValidationError('Asterisk-Container-Preflight ist erforderlich, aber nicht konfiguriert.');
    }
    return;
  }

  fs.mkdirSync(preflightDir, { recursive: true, mode: 0o750 });
  makeReadableByAsterisk(preflightDir, 0o750);
  const request = path.join(preflightDir, `${staged.deploymentId}.request`);
  const requestTemp = `${request}.tmp`;
  const result = path.join(preflightDir, `${staged.deploymentId}.result`);
  fs.writeFileSync(requestTemp, `${staged.deploymentId}\n`, { encoding: 'utf8', mode: 0o640, flag: 'wx' });
  makeReadableByAsterisk(requestTemp, 0o640);
  fs.renameSync(requestTemp, request);

  try {
    const deadline = Date.now() + Number(process.env.ASTERISK_PREFLIGHT_TIMEOUT_MS ?? 65_000);
    while (Date.now() < deadline) {
      if (fs.existsSync(result)) {
        const response = fs.readFileSync(result, 'utf8').trim();
        if (response === 'ok') return;
        throw new GeneratedConfigValidationError(
          `Asterisk-Container-Preflight fehlgeschlagen: ${response.replace(/^error\s*/i, '').slice(0, 1000)}`
        );
      }
      await wait(100);
    }
    throw new GeneratedConfigValidationError('Asterisk-Container-Preflight hat das Zeitlimit überschritten.');
  } finally {
    for (const candidate of [requestTemp, request, result]) {
      try {
        fs.unlinkSync(candidate);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
      }
    }
  }
}

async function runtimeHealth(ami: AmiClient, topology: Topology, expectedDeploymentId?: string): Promise<void> {
  const version = await ami.runCommand('core show version');
  if (!/Asterisk/i.test(version)) throw new Error('Asterisk antwortet nicht mit einer Runtime-Version.');
  const dialplan = await ami.runCommand('dialplan show internal');
  if (!/\[ Context 'internal'|include.*entrypoints|Calling/i.test(dialplan)) {
    throw new Error('Aktiver Dialplan enthält den internen Kontext nicht.');
  }
  if (expectedDeploymentId) {
    const canary = await ami.runCommand(`dialplan show ${expectedDeploymentId}@essentials_deploy_canary`);
    if (!canary.includes(expectedDeploymentId)) {
      throw new Error(`Runtime-Canary für Deployment ${expectedDeploymentId} ist nicht aktiv.`);
    }
  }
  const expectedEndpoints = topology.nodes.filter((node) => node.type === 'extension').length;
  const endpoints = await ami.getEndpointStatuses();
  if (endpoints.length < expectedEndpoints) {
    throw new Error(`Runtime meldet nur ${endpoints.length}/${expectedEndpoints} erwarteten PJSIP-Endpunkten.`);
  }
}

export interface DeployResult {
  deployed: boolean;
  configsWritten: boolean;
  activated: boolean;
  reloaded: boolean;
  runtimeHealthy: boolean;
  rolledBack: boolean;
  deploymentId: string;
  checksum?: string;
  error?: string;
  rollbackError?: string;
}

export async function deployTopology(
  topology: Topology,
  revision: number,
  actor: Actor,
  database: PbxDatabase,
  dependencies: { getAmi?: () => Promise<AmiClient> } = {}
): Promise<DeployResult> {
  const deploymentId = crypto.randomUUID();
  database.createDeployment(deploymentId, revision, actor);
  let staged: StagedConfig | undefined;
  let previousTarget: string | null = null;
  let activated = false;
  let reloaded = false;
  let rollbackError: string | undefined;
  try {
    staged = stageGeneratedConfigs(topology, deploymentId);
    await validateStagedWithAsterisk(staged);
    const ami = await (dependencies.getAmi ?? getAmiClient)();
    await ami.runCommand('core show version');
    previousTarget = readCurrentTarget();
    switchCurrent(staged.target, deploymentId);
    activated = true;

    const oneShotCorruptionMarker = path.join(configOutDir(), '.test-corrupt-next-deploy');
    if (
      process.env.PBX_ENV === 'test' &&
      (process.env.PBX_TEST_CORRUPT_AFTER_PREFLIGHT === 'true' || fs.existsSync(oneShotCorruptionMarker))
    ) {
      try {
        fs.unlinkSync(oneShotCorruptionMarker);
      } catch (markerError) {
        if ((markerError as NodeJS.ErrnoException).code !== 'ENOENT') throw markerError;
      }
      const extensionConfig = path.join(staged.directory, CONFIG_FILES.extensions);
      const corrupted = fs
        .readFileSync(extensionConfig, 'utf8')
        .replace('[essentials_deploy_canary]', '[synthetic-broken-section');
      fs.writeFileSync(extensionConfig, corrupted, 'utf8');
    }

    await ami.deployReload();
    reloaded = true;
    await runtimeHealth(ami, topology, staged.deploymentId);
    const lastGoodTemp = path.join(configOutDir(), `.last-good-${deploymentId}`);
    fs.symlinkSync(staged.target, lastGoodTemp, 'dir');
    fs.renameSync(lastGoodTemp, path.join(configOutDir(), 'last-good'));
    database.markDeploymentActive(revision);
    const result: DeployResult = {
      deployed: true,
      configsWritten: true,
      activated: true,
      reloaded: true,
      runtimeHealthy: true,
      rolledBack: false,
      deploymentId,
      checksum: staged.checksum,
    };
    database.finishDeployment(deploymentId, 'success', staged.checksum, { ...result });
    database.audit(actor, 'deploy', `revision:${revision}`, 'success', {
      deploymentId,
      checksum: staged.checksum,
    });
    return result;
  } catch (error) {
    let rolledBack = false;
    if (activated) {
      try {
        switchCurrent(previousTarget, `${deploymentId}-rollback`);
        const ami = await (dependencies.getAmi ?? getAmiClient)();
        await ami.deployReload();
        if (previousTarget) {
          const previousDeploymentId = path.basename(previousTarget);
          await runtimeHealth(
            ami,
            database.materializedTopology(database.currentTopology().lastGoodRevision ?? undefined),
            previousDeploymentId === 'bootstrap' ? undefined : previousDeploymentId
          );
        }
        rolledBack = true;
      } catch (rollbackFailure) {
        rollbackError = (rollbackFailure as Error).message;
      }
    }
    const result: DeployResult = {
      deployed: false,
      configsWritten: !!staged,
      activated,
      reloaded,
      runtimeHealthy: false,
      rolledBack,
      deploymentId,
      checksum: staged?.checksum,
      error: (error as Error).message,
      rollbackError,
    };
    database.finishDeployment(deploymentId, rolledBack ? 'failed-rolled-back' : 'failed', staged?.checksum ?? null, { ...result });
    database.audit(actor, 'deploy', `revision:${revision}`, 'failure', {
      deploymentId,
      error: result.error,
      rolledBack,
      rollbackError,
    });
    return result;
  }
}
