#!/bin/sh
set -e

AMI_USERNAME="${AMI_USERNAME:-visualpbx}"
AMI_SECRET="${AMI_SECRET:-}"

if [ -z "$AMI_SECRET" ] || [ "$AMI_SECRET" = "visualpbx" ]; then
  echo "ERROR: a non-default AMI_SECRET is required." >&2
  exit 1
fi
case "$AMI_USERNAME" in
  ''|*[!A-Za-z0-9_.-]*)
    echo "ERROR: AMI_USERNAME must contain only letters, digits, dot, underscore, or hyphen." >&2
    exit 1
    ;;
esac
if [ "${#AMI_USERNAME}" -gt 64 ]; then
  echo "ERROR: AMI_USERNAME must not exceed 64 characters." >&2
  exit 1
fi
case "$AMI_SECRET" in
  *[!A-Za-z0-9_.@%+=,:-]*)
    echo "ERROR: AMI_SECRET contains characters that cannot be rendered safely into manager.conf." >&2
    exit 1
    ;;
esac
if [ "${#AMI_SECRET}" -lt 16 ] || [ "${#AMI_SECRET}" -gt 256 ]; then
  echo "ERROR: AMI_SECRET must contain 16 to 256 characters." >&2
  exit 1
fi

# Render manager.conf from the template so credentials are not baked into the image.
sed -e "s/__AMI_USERNAME__/${AMI_USERNAME}/g" \
    -e "s/__AMI_SECRET__/${AMI_SECRET}/g" \
    /etc/asterisk/manager.conf.template > /etc/asterisk/manager.conf
chmod 640 /etc/asterisk/manager.conf

mkdir -p /etc/asterisk/generated/versions/bootstrap
if [ ! -L /etc/asterisk/generated/current ]; then
  printf '%s\n\n' '; AUTO-GENERATED by Simple Calls bootstrap. Do not edit by hand.' \
    > /etc/asterisk/generated/versions/bootstrap/pjsip_generated.conf
  printf '%s\n\n[internal]\ninclude => entrypoints\n\n[entrypoints]\n\n[callflow]\n' \
    '; AUTO-GENERATED by Simple Calls bootstrap. Do not edit by hand.' \
    > /etc/asterisk/generated/versions/bootstrap/extensions_generated.conf
  printf '%s\n\n' '; AUTO-GENERATED by Simple Calls bootstrap. Do not edit by hand.' \
    > /etc/asterisk/generated/versions/bootstrap/queues_generated.conf
  printf '%s\n\n' '; AUTO-GENERATED by Simple Calls bootstrap. Do not edit by hand.' \
    > /etc/asterisk/generated/versions/bootstrap/voicemail_generated.conf
  ln -s versions/bootstrap /etc/asterisk/generated/current
fi

# Prompts uploaded through the web UI land here (shared volume). Asterisk reaches
# them via the /usr/share/asterisk/sounds/custom symlink, i.e. as "custom/<name>".
mkdir -p /usr/local/share/asterisk/sounds
mkdir -p /usr/share/asterisk/moh

chown -R asterisk:asterisk /etc/asterisk/generated /etc/asterisk/manager.conf \
  /usr/local/share/asterisk/sounds \
  /var/lib/asterisk /var/log/asterisk /var/spool/asterisk 2>/dev/null || true

# A private filesystem handshake lets the backend ask this container to load a
# staged candidate in an isolated Asterisk process before activation. No Docker
# socket, shell endpoint or extra network listener is exposed.
/preflight-worker.sh &

exec /usr/sbin/asterisk -f -U asterisk -G asterisk
