[general]
format=wav49|gsm|wav
serveremail=asterisk@essentials-calls.local
attach=yes
skipms=3000
maxsilence=10
silencethreshold=128
maxlogins=3

[default]
#include generated/current/voicemail_generated.conf
